import { dirname } from 'node:path';
import { fileURLToPath } from 'node:url';
import { FlatCompat } from '@eslint/eslintrc';

const compat = new FlatCompat({ baseDirectory: dirname(fileURLToPath(import.meta.url)) });

const config = [
  {
    ignores: [
      '.next/**',
      'node_modules/**',
      'next-env.d.ts',
      'themes/*/theme.css',
      // Generated by `astryx theme build`.
      'themes/*/*.js',
      'themes/*/*.d.ts',
    ],
  },
  ...compat.extends('next/core-web-vitals', 'next/typescript'),
  {
    rules: {
      // Enforces the "all data access goes through lib/api" convention.
      'no-restricted-syntax': [
        'error',
        {
          selector: "CallExpression[callee.name='fetch']",
          message:
            'Do not call fetch() directly. All data access goes through lib/api/* (see lib/api/client.ts).',
        },
      ],
    },
  },
  {
    // The single HTTP client is the one place app code may call fetch().
    // Build-time scripts are not app data access — they never run in a request.
    // The service worker runs OUTSIDE the app entirely: it has no module graph,
    // cannot import lib/api, and intercepting fetch is its whole purpose.
    files: ['lib/api/client.ts', 'scripts/**/*.mjs', 'public/sw.js'],
    rules: { 'no-restricted-syntax': 'off' },
  },
];

export default config;
