'use client';

import NextLink from 'next/link';
import { Theme } from '@astryxdesign/core/theme';
import { LinkProvider } from '@astryxdesign/core/Link';

// The BUILT theme (generated by `pnpm theme:build`), not the source theme.
// The built module skips runtime style injection and relies on the compiled
// theme.css imported in globals.css — which is what makes the theme present at
// first paint under SSR. Importing the source theme instead costs a large
// client chunk and a flash of unthemed content.
import { CartProvider } from '@/lib/cart/CartProvider';
import { kokofreshTheme } from '@/themes/kokofresh/kokofresh';

/**
 * Theme + routing providers.
 *
 * LinkProvider wires Astryx's Link to next/link so client-side navigation works
 * throughout the design system. Swapping brands means pointing these imports at
 * another themes/<brand>/ folder — no component changes.
 */
export function Providers({ children }: { children: React.ReactNode }) {
  return (
    <Theme theme={kokofreshTheme}>
      <LinkProvider component={NextLink}>
        <CartProvider>{children}</CartProvider>
      </LinkProvider>
    </Theme>
  );
}
